# Generated by Django 5.0.2 on 2024-07-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_anpr_plate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anpr',
        ),
    ]
