# Generated by Django 3.2.12 on 2025-01-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_boomsig'),
    ]

    operations = [
        migrations.AddField(
            model_name='boomsig',
            name='barrier_open_count',
            field=models.IntegerField(default=0),
        ),
    ]
