# Generated by Django 4.1 on 2025-02-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_users',
        ),
    ]
