# Generated by Django 5.0.2 on 2024-07-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anpr',
            name='plate',
            field=models.TextField(),
        ),
    ]
