# Generated by Django 3.2.12 on 2025-01-29 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_carlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boomsig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entryboom', models.CharField(default='N', max_length=1)),
                ('entrysynctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('exitboom', models.CharField(default='N', max_length=1)),
                ('exitsynctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'boomsig',
            },
        ),
    ]
