# Generated by Django 4.1 on 2025-02-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_boomsig_barrier_open_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrierOpenLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_logs', to='dashboard.boomsig')),
            ],
            options={
                'db_table': 'barrieropenlog',
            },
        ),
    ]
